title: Binomial-7
pulseSeq:
  - t: 0
    FA: 1.4
    dur: 0.5
  - t: 2.3
    FA: 8.4
    dur: 0.5
  - t: 4.6
    FA: 21.1
    dur: 0.5
  - t: 6.9
    FA: 28.1
    dur: 0.5
  - t: 9.2
    FA: 21.1
    dur: 0.5
  - t: 11.5
    FA: 8.4
    dur: 0.5
  - t: 13.8
    FA: 1.4
    dur: 0.5
TR: 20
B0: 1.5
components:
  - name: water
    CS: 0.0
  - name: fat
    CS: -3.40389262
nIsochromats: 15
isochromatStep: 0.03
speed: 0.001
output:
  - type: 3D
    file: binomial7_3D.gif