title: Diffusion
TR: 90
nTR: 1
nDummies: 0
B0: 1.5
pulseSeq:
  - t: 0
    FA: 90
    dur: 2
    B1: 'RF/exc_min_phase.yml'
  - t: 5
    Gx: 30
    dur: 24
  - t: 37
    FA: 180
    B1: 'RF/ref.yml'
    dur: 3
    phase: 90
  - t: 40
    Gx: 30
    dur: 24
components:
  - name: still
    T1: 3000
    T2: 300
  - name: diffusive
    T1: 3000
    T2: 300
    Dx: 0.001
    Dy: 0.001
nIsochromats: 8
isochromatStep: 0.03
locSpacing: 0.001
locations:
  'still':
    [[.00, .00, .75, .75, .75, .75, .00],
     [.75, .75, .75, .75, .75, .75, .75],
     [.75, .75, .00, .00, .00, .75, .75],
     [.75, .75, .00, .00, .00, .75, .75],
     [.75, .75, .00, .00, .00, .75, .75],
     [.75, .75, .75, .75, .75, .75, .75],
     [.00, .75, .75, .75, .75, .00, .00]]
  'diffusive':
    [[.00, .00, .00, .00, .00, .00, .00],
     [.00, .00, .00, .00, .00, .00, .00],
     [.00, .00, .75, .75, .75, .00, .00],
     [.00, .00, .75, .75, .75, .00, .00],
     [.00, .00, .75, .75, .75, .00, .00],
     [.00, .00, .00, .00, .00, .00, .00],
     [.00, .00, .00, .00, .00, .00, .00]]
speed: .01
maxRFspeed: .002
output:
  - type: 3D
    file: diffusion_3D.gif
  - type: psd
    file: diffusion_psd.gif