title: Fat and Water Precession (1.5 T)
pulseSeq:
  - t: 0
    FA: 90
    dur: 0.1
TR: 15
B0: 1.5 
components:
  - name: water
    CS: 0.0
    T1: 870
    T2: 47
  - name: fat
    CS: 3.4
    T1: 260
    T2: 84
speed: 0.001
maxRFspeed: 0.0001
output:
  - type: 3D
    file: fatwater_3D.gif
  - type: xy
    file: fatwater_tra.gif