title: FSE
pulseSeq:
  - t: 0
    FA: 90
    B1: 'RF/exc_min_phase.yml'
    dur: 3
  - t: 10
    FA: 180
    B1: 'RF/ref.yml'
    dur: 3
  - t: 30
    FA: 180
    B1: 'RF/ref.yml'
    dur: 3
  - t: 50
    FA: 180
    B1: 'RF/ref.yml'
    dur: 3
  - t: 70
    FA: 180
    B1: 'RF/ref.yml'
    dur: 3
TR: 130
B0: 1.5
nIsochromats: 30
isochromatStep: 0.02
speed: 0.01
output:
  - type: 3D
    file: FSE_3D.gif