title: Spin Echo
pulseSeq:
    - t: 0
      FA: 90
      B1: 'RF/exc_min_phase.yml'
      dur: 3
    - t: 10
      FA: 180
      B1: 'RF/ref.yml'
      dur: 3
      phase: 90
TR: 300
B0: 3
components:
    - T1: 700
      T2: 100
nIsochromats: 20
isochromatStep: 0.01
speed: 0.01
background:
  color: white
output: 
   - type: 3D
     file: SE_3D.gif
   - type: xy
     abs: true
     normalize: False
     freeze: [300.0]
     file: SE_xy_abs.gif
   - type: xy
     abs: false
     freeze: [300.0]
     file: SE_xy_RI.gif
   - type: z
     freeze: [300.0]
     file: SE_z.gif
   - type: psd
     freeze: [300.0]
     file: SE_psd.gif
  - type: raw
    file: SE_raw.npy