title: Spatial Excitation
pulseSeq:
  - t: 0
    FA: 90
    B1: 'RF/exc_min_phase.yml'
    dur: 3
    Gx: 30
TR: 10
B0: 1.5
locations:
  [[ 0,  0, .7, .7, .7,  0,  0],
   [ 0, .7, .7, .7, .7, .7,  0],
   [.7, .7, .7, .7, .7, .7, .7],
   [.7, .7, .7, .7, .7, .7, .7],
   [.7, .7, .7, .7, .7, .7, .7],
   [ 0, .7, .7, .7, .7, .7,  0],
   [ 0,  0, .7, .7, .7,  0,  0]]
speed: 0.005
output:
  - type: 3D
    file: SpExc_3D.gif
  - type: psd
    file: SpExc_psd.gif